import { css } from '@emotion/react';
import Head from 'next/head';
// import Image from 'next/image';
// import Link from 'next/link';
import Layout from '../components/Layout';

// import portada from '../public/images/portada.jpg';

// import { myGlobalStyles } from '../styles/myGlobalStyles';

const main = css`
  margin-top: 0;
  padding-top: 5rem;
  width: 100vw;
  height: 87vh;
  background-image: url('/images/portada.jpg');
  background-size: cover;
  position: relative;
`;

const title = css`
  font-family: 'New Tegomin';
  color: white;
  font-weight: 700;
  font-size: 4.6rem;
  text-align: center;
  margin-top: -0.8rem;
`;

// const portadaStyle = css`
//   min-height: 80vh;
//   height: 15rem !important;
//   width: 10rem;
// `;

export default function Home(props) {
  return (
    <div>
      <Head>
        <title>Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <Layout cartCount={props.cartCount} setCartCount={props.setCartCount}>
        <main css={main}>
          {/* <Image css={portadaStyle} src={portada} alt="portada" /> */}
          <p css={title}>Travel the World</p>
        </main>
      </Layout>
    </div>
  );
}
