import { css } from '@emotion/react';
import Head from 'next/head';
import Layout from '../components/Layout';

const main = css`
  margin-top: 0;
  padding-top: 5rem;
  width: 100vw;
  height: 87vh;
  background-image: url('/images/portada.jpg');
  background-size: cover;
  position: relative;
  overflow: hidden;
`;

const title = css`
  font-family: 'New Tegomin';
  color: white;
  font-weight: 700;
  font-size: 4.6rem;
  text-align: center;
  margin-top: -0.8rem;
  margin-bottom: 0;
  z-index: -5;
`;

const headerImage = css`
  width: 30%;
  margin-left: 70rem;
  padding-bottom: 10rem !important;
  animation: image-float 220s infinite;
  @keyframes image-float {
    0% {
      transform: translateZ(50%);
      opacity: 1;
    }

    40% {
      transform: translateZ(-9.7rem) translateX(-150rem) translateY(-85%);
    }
    70% {
      transform: perspective(-1500rem) translateZ(-800rem);
    }
    80% {
      transform: translateZ(-50rem) translateX(100rem);
    }
    100% {
      transform: translateZ(40rem);
    }
  }
`;

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
        <link href="..styles/style.css" rel="stylesheet" key="test" />
      </Head>

      <Layout>
        <main css={main}>
          <p css={title}>Travel the World</p>
          <img
            className="headerImage"
            src="/images/air-balloon.png"
            alt="Header"
            css={headerImage}
          />
        </main>
      </Layout>
    </div>
  );
}
